swagger: '2.0'
info:
  version: 1.0.0
  title: eGov Household Registry Service
  description: >
    This module facilitates household registry for egov.
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
schemes:
  - https
basePath: /household
x-common-path: >-
  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml
paths:
  #########################################
  /v1/_create:
    post:
      summary: Create a Household Registry.
      description: Registers a Household. On successful Household Registered, Ok response is returned.
      parameters:
        - name: householdCreateRegistryRequest
          in: "body"
          description: Details of the household and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/HouseHoldRequest'
      responses:
        '200':
          description: Household created successfully.
          schema:
            $ref: '#/definitions/HouseholdResponseWithResponseInfo'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Household Registry
  /v1/_update:
    post:
      summary: Update A Household Registry.
      description: Update A Household Registry, Ok response is returned.
      parameters:
        - name: householdRegistryUpdateRequest
          in: "body"
          description: Details of the household registry and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/HouseholdUpdateRequest'
      responses:
        '200':
          description: Updated Household successfully.
          schema:
            $ref: '#/definitions/HouseholdResponseWithResponseInfo'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Household Registry
  /v1/_search:
    post:
      summary: Search Household Registry.
      description: Search Household Registry Ok response is returned.
      parameters:
        - name: householdSearchRequest
          in: "body"
          description: Search Criteria for Household and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/HouseholdSearchRequest'
      responses:
        '200':
          description: Feteched Search Household.
          schema:
            $ref: '#/definitions/HouseholdRegistrationSearchResponse'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Household Registry

  #########################################
  /indiviudal/v1/_create:
    post:
      summary: Add an Individual to Household.
      description: Add an Individual to Household. On successful Individual addition, Ok response is returned.
      parameters:
        - name: addIndividualToHousehold
          in: "body"
          description: Adding of the individuals to household and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/IndividualRequest'
      responses:
        '200':
          description: Individual added successfully.
          schema:
            $ref: '#/definitions/HouseholdResponseWithResponseInfo'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Individual Management
  /indiviudal/v1/_update:
    post:
      summary: Update An Individual.
      description: Update An Individual, Ok response is returned.
      parameters:
        - name: individualUpdateRequest
          in: "body"
          description: Details of the individual  and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/IndividualUpdateRequest'
      responses:
        '200':
          description: Updated Individual successfully.
          schema:
            $ref: '#/definitions/HouseholdResponseWithResponseInfo'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Individual Management

#########################################
definitions:
  HouseHoldRegistry:
    description: A representation of Household.
    type: object
    properties:
      noOfIndividuals:
        type: integer
        example: 4
      address:
        type: string
        example: 'Address XYZ'
      dateOfRegistration:
        type: integer
        format: int64
        example: 1663218161
      location:
        $ref: '#/definitions/Location'
      administrativeUnit:
        type: string
        example: 'SOLIMBO'
      individuals:
        type: array
        items:
          $ref: '#/definitions/Individuals'
      auditDetails:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/AuditDetails
  IndividualRegistration:
    description: A representation of Individual Registration.
    type: object
    properties:
      campaignId:
        type: string
        example: 'CAMP-001'
      name:
        type: string
        example: 'John Doe'
      dateOfBirth:
        type: integer
        format: int64
        example: 1663218161
      gender:
        type: string
        example: "MALE"
        enum:
          - MALE
          - FEMALE
          - OTHERS
      address:
        type: string
        example: 'Address XYZ'
      dateOfRegistration:
        type: integer
        format: int64
        example: 1663218161
      location:
        $ref: '#/definitions/Location'
      administrativeUnit:
        type: string
        example: 'SOLIMBO'
      identifiers:
        type: array
        items:
          $ref: '#/definitions/Identifiers'
      auditDetails:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/AuditDetails
  Individuals:
    type: object
    properties:
      name:
        type: string
      dateOfBirth:
        type: string
        example: 'YYYYMMDD'
      mode:
        type: string
        example: 'CREATE'
        enum:
          - CREATE
          - UPDATE
          - DELETE
      gender:
        type: string
        example: 'MALE'
        enum:
          - MALE
          - FEMALE
          - OTHERS
      isHead:
        type: boolean
        example: true
      identifiers:
        type: array
        items:
          $ref: '#/definitions/Identifiers'
  IndividualsResponse:
    type: object
    properties:
      name:
        type: string
      dateOfBirth:
        type: string
        example: 'YYYYMMDD'
      individualId:
        type: string
        example: 'ID-1'
      gender:
        type: string
        example: 'MALE'
        enum:
          - MALE
          - FEMALE
          - OTHERS
      isHead:
        type: boolean
        example: true
      identifiers:
        type: array
        items:
          $ref: '#/definitions/Identifiers'
  IndividualUpdateBody:
    type: object
    properties:
      name:
        type: string
      dateOfBirth:
        type: string
        example: 'YYYYMMDD'
      individualId:
        type: string
        example: 'ID-1'
      gender:
        type: string
        example: 'MALE'
        enum:
          - MALE
          - FEMALE
          - OTHERS
      isHead:
        type: boolean
        example: true
      identifiers:
        type: array
        items:
          $ref: '#/definitions/Identifiers'

  Identifiers:
    type: object
    properties:
      type:
        type: string
        example: 'SYSTEM_GENERATED'
      identifierId:
        type: string
        example: 'ABCD-1212'
  Location:
    type: object
    properties:
      latitude:
        type: integer
        format: int64
        example: 18.22
      longitude:
        type: integer
        format: int64
        example: 71.00
      accuracy:
        type: integer
        format: int64
        example: 9
  AdditonalFields:
    type: object
    properties:
      schema:
        type: string
        example: 'HOUSEHOLD'
      version:
        type: integer
        example: 2
      fields:
        type: array
        items:
          type: object
          $ref: '#/definitions/Field'

  Field:
    type: object
    properties:
      key:
        type: string
        example: height
      value:
        type: string
        example: 180

  HouseholdResponse:
    type: object
    allOf:
      - type: object
        properties:
          householdId:
            type: string
            example: 'H-ID-1'
      - $ref: '#/definitions/HouseHoldRegistry'
      - type: object
        properties:
          individuals:
            type: array
            items:
              $ref: '#/definitions/IndividualsResponse'

  #########################################
  HouseHoldRequest:
    description: >-
      The request object, containing all necessary information for creating an Household and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      household:
        $ref: '#/definitions/HouseHoldRegistry'
    required:
      - householdRegistration

  HouseholdUpdateRequest:
    description: >-
      The request object, containing all necessary information for updating an Household and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      household:
        type: object
        properties:
          householdId:
            type: string
            example: 'H-ID-1'
          noOfIndividuals:
            type: integer
            example: 4
          address:
            type: string
            example: 'Address'
          dateOfRegistration:
            type: integer
            format: int64
            example: 1663218161
          location:
            $ref: '#/definitions/Location'
          administrativeUnit:
            type: string
            example: 'SOLIMBO'
    required:
      - household

  HouseholdSearchRequest:
    description: >-
      The request object, containing all necessary information for updating an Household and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      householdRegistrationSearchCriteria:
        type: object
        properties:
          householdId:
            type: string
            example: 'H-ID'
          createdBy:
            type: string
            example: 'UUID'
          limit:
            type: integer
            example: 5
          offset:
            type: integer
            example: 5

  HouseholdRegistrationSearchResponse:
    description: >-
      The Household response object.
    properties:
      responseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo
      totalCount:
        type: integer
        example: 1
      households:
        type: array
        items:
          type: object
          $ref: '#/definitions/HouseholdResponse'

  HouseholdResponseWithResponseInfo:
    description: >-
      The household response object.
    properties:
      responseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo
      household:
        $ref: '#/definitions/HouseholdResponse'

  #########################################

  IndividualRequest:
    description: >-
      The request object, containing all necessary information for creating an Individual and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      household:
        type: object
        properties:
          householdId:
            type: string
            example: "H-ID-1"
          individuals:
            type: array
            items:
              $ref: '#/definitions/IndividualsResponse'
    required:
      - individualRegistration
  IndividualUpdateRequest:
    description: >-
      The request object, containing all necessary information for updating an individual and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      household:
        type: object
        allOf:
          - type: object
            properties:
              household:
                type: string
                example: 'H-ID'
              individual:
                type: object
                $ref: '#/definitions/IndividualUpdateBody'
    required:
      - household