swagger: '2.0'
info:
  version: 1.0.0
  title: eGov Individual Registry Service
  description: >
    This module facilitates individual registry for egov.
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
schemes:
  - https
basePath: /individual
x-common-path: >-
  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml
paths:
  #########################################
  /v1/_create:
    post:
      summary: Create a Individual Registry.
      description: Registers a Individual. On successful Individual Registered, Ok response is returned.
      parameters:
        - name: individualCreateRegistryRequest
          in: "body"
          description: Details of the individual and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/IndividualRequest'
      responses:
        '200':
          description: Individual created successfully.
          schema:
            $ref: '#/definitions/IndividualResponseWithResponseInfo'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Individual Registry
  /v1/_update:
    post:
      summary: Update A Individual Registry.
      description: Update A Individual Registry, Ok response is returned.
      parameters:
        - name: indiviualRegistryUpdateRequest
          in: "body"
          description: Details of the individual registry and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/IndividualUpdateRequest'
      responses:
        '200':
          description: Updated Individual successfully.
          schema:
            $ref: '#/definitions/IndividualResponseWithResponseInfo'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Individual Registry
  /v1/_search:
    post:
      summary: Search Individual Registry.
      description: Search Individual Registry Ok response is returned.
      parameters:
        - name: individualSearchCriteria
          in: "body"
          description: Search Criteria for Individual and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/IndividualSearchRequest'
      responses:
        '200':
          description: Feteched Search Individual.
          schema:
            $ref: '#/definitions/IndividualRegistrationSearchResponse'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Individual Registry


#########################################
definitions:
  Individuals:
    type: object
    properties:
      name:
        type: string
        example: "John Doe"
      dateOfBirth:
        type: string
        example: 'YYYYMMDD'
      gender:
        type: string
        example: 'MALE'
        enum:
          - MALE
          - FEMALE
          - OTHERS
      identifiers:
        type: array
        items:
          $ref: '#/definitions/Identifiers'
      address:
        type: string
        example: 'Address'
      dateOfRegistration:
        type: integer
        format: int64
        example: 1663218161
      location:
        $ref: '#/definitions/Location'
      administrativeUnit:
        type: string
        example: 'SOLIMBO'
  IndividualsResponse:
    type: object
    properties:
      individualId:
        type: string
        example: "R-ID-1"
      name:
        type: string
        example: "John Doe"
      dateOfBirth:
        type: string
        example: 'YYYYMMDD'
      gender:
        type: string
        example: 'MALE'
        enum:
          - MALE
          - FEMALE
          - OTHERS
      identifiers:
        type: array
        items:
          $ref: '#/definitions/Identifiers'
      address:
        type: string
        example: 'Address'
      dateOfRegistration:
        type: integer
        format: int64
        example: 1663218161
      location:
        $ref: '#/definitions/Location'
      administrativeUnit:
        type: string
        example: 'SOLIMBO'
  IndividualUpdateBody:
    type: object
    properties:
      name:
        type: string
        example: "John Doe"
      dateOfBirth:
        type: string
        example: 'YYYYMMDD'
      individualId:
        type: string
        example: 'ID-1'
      gender:
        type: string
        example: 'MALE'
        enum:
          - MALE
          - FEMALE
          - OTHERS
      isHead:
        type: boolean
        example: true
      identifiers:
        type: array
        items:
          $ref: '#/definitions/Identifiers'

  Identifiers:
    type: object
    properties:
      type:
        type: string
        example: 'SYSTEM_GENERATED'
      identifierId:
        type: string
        example: 'ABCD-1212'
  Location:
    type: object
    properties:
      latitude:
        type: integer
        format: int64
        example: 18.22
      longitude:
        type: integer
        format: int64
        example: 71.00
      accuracy:
        type: integer
        format: int64
        example: 9

  #########################################
  IndividualSearchRequest:
    description: >-
      The request object, containing all necessary information for updating an Individual and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      individualSearchCriteria:
        allOf:
          - type: object
            $ref: '#/definitions/IndividualUpdateBody'
          - type: object
            properties:
              createdBy:
                type: string
                example: 'UUID'
              limit:
                type: integer
                example: 5
              offset:
                type: integer
                example: 5

  IndividualRegistrationSearchResponse:
    description: >-
      The Individual response object.
    properties:
      responseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo
      totalCount:
        type: integer
        example: 0
      individuals:
        type: array
        items:
          type: object
          $ref: '#/definitions/IndividualsResponse'

  IndividualResponseWithResponseInfo:
    description: >-
      The individual response object.
    properties:
      responseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo
      individual:
        $ref: '#/definitions/IndividualsResponse'

  #########################################

  IndividualRequest:
    description: >-
      The request object, containing all necessary information for creating an Individual and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      individual:
        type: object
        $ref: '#/definitions/Individuals'
    required:
      - individualRegistration
  IndividualUpdateRequest:
    description: >-
      The request object, containing all necessary information for updating an individual and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      individual:
        type: object
        allOf:
          - type: object
            properties:
              individual:
                type: object
                $ref: '#/definitions/IndividualUpdateBody'
    required:
      - individual