swagger: '2.0'
info:
  version: 1.0.0
  title: eGov Campaign Service
  description: >
    This module facilitates campaign management for egov.
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
schemes:
  - https
basePath: /campaigns
x-common-path: >-
  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml
paths:
  #########################################
  /v1/_create:
    post:
      summary: Create a campaign.
      description: Create's a campaign. On successful campaign creation, Ok response is returned.
      parameters:
        - name: campaignRequest
          in: "body"
          description: Details of the campaign and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/CampaignRequest'
      responses:
        '200':
          description: Campaign created successfully.
          schema:
            $ref: '#/definitions/CampaignResponseWithResponseInfo'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Campaigns
  /v1/_update:
    post:
      summary: Update A Campaign.
      description: Update A Campaign, Ok response is returned.
      parameters:
        - name: campaignUpdateRequest
          in: "body"
          description: Details of the campaign and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/CampaignUpdateRequest'

      responses:
        '200':
          description: Updated campaign successfully.
          schema:
            $ref: '#/definitions/CampaignResponseWithResponseInfo'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Campaigns
  /v1/_search:
    post:
      summary: Search Campaigns.
      description: Search Campaigns Ok response is returned.
      parameters:
        - name: campaignSearchRequest
          in: "body"
          description: Search Criteria for campaign and RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/CampaignSearchRequest'
      responses:
        '200':
          description: Feteched Search Campaigns.
          schema:
            $ref: '#/definitions/CampaignSearchResponse'
        '400':
          description: Bad request
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
        '500':
          description: Internal server error
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Campaigns
#########################################
definitions:

  CampaignResponse:
    type: object
    allOf:
      - type: object
        properties:
          id:
            type: string
            example: 'CAMPAIGN-ID-1'
      - $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/commons.yml#/definitions/Campaign'

  #########################################
  CampaignRequest:
    description: >-
      The request object, containing all necessary information for creating an campaign and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      campaign:
        $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/commons.yml#/definitions/Campaign'
    required:
      - Campaign

  CampaignUpdateRequest:
    description: >-
      The request object, containing all necessary information for updating an campaign and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      campaign:
        type: object
        allOf:
          - type: object
            properties:
              id:
                type: string
                example: 'CAMPAIGN-ID'
          - $ref: 'https://raw.githubusercontent.com/digit-egov/health-api-specs/main/commons.yml#/definitions/Campaign'
    required:
      - campaign

  CampaignSearchRequest:
    description: >-
      The request object, containing all necessary information for updating an campaign and the request body metadata
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      campaignSearchCriteria:
        type: object
        properties:
          id:
            type: string
            example: 'CAMPAIGN-ID'
          name:
            type: string
            example: 'LLIN 2022'
          type:
            type: string
            example: 'LLIN'
          status:
            type: string
            example: 'CREATED'
          limit:
            type: number
            example: 0
          offset:
            type: number
            example: 0
    required:
      - campaignSearchCriteria
  RequestInfoWrapper:
    description: >-
      Wrapper for Request Info
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo


  CampaignSearchResponse:
    description: >-
      The campaign response objecy.
    properties:
      responseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo
      totalCount:
        type: number
        example: 1
      campaigns:
        type: array
        items:
          type: object
          $ref: '#/definitions/CampaignResponse'

  CampaignResponseWithResponseInfo:
    description: >-
      The campaign response object.
    properties:
      responseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo
      campaign:
        $ref: '#/definitions/CampaignResponse'

#########################################